### ISSUE TITLE
La CI est cassée car Python 3.9.4 n'est plus disponible

### ISSUE THREAD

**Issue by thbar** [etalab/schema-comptage-velo#2]
L'action setup Python casse (voir #1). Python 3.9.5 est sorti, et du coup apparemment Python 3.9.4 n'est plus disponible (à vérifier).

Point intéressant ici https://github.com/actions/setup-python/issues/210

À creuser.

**Comment by abulte** [comment]
Why not use a base image with Python 3.9 instead of installing it in the workflow?

**Comment by thbar** [comment]
I just used what has been done in the previous schema, which provides a way to work locally easily with the exact same version to make it easier to reproduce errors, but yes it could also be done that way.

**Comment by thbar** [comment]
Corrigé dans #3. Je préfère rester sur l'action `setup-python` qui permet de reproduire facilement la version exacte utilisée en développement, et il se trouve que la v2 de l'action gère parfaitement ça.
